### ISSUE TITLE
修正点

### ISSUE THREAD

**Issue by besutome** [YutamaKotaro/slides#1]
## 直すべきのような気がする箇所

**1**

`jsファイルはreact-scriptsパッケージ経由でwebpackを利用して読み込まれています`

この文章があると混乱させるだけのような気がするので思い切って省くか、
もう少し詳しく`react-scripts`や`webpack`の説明がいるかと思います。

**2**

`renderメソッドは画面描写の時に実行されるので、renderメソッドの中でsetStateを使わないでください。
使うとどうなるかはご想像にお任せします。。。。`

口頭で説明するなら上記のままでも大丈夫です！
そのつもりがないなら、簡単にでも説明文を書くか、`使うとどうなるかはご想像にお任せします。。。。`
の部分は省いたほうがいいと思います。

**3**

`Reactあるあるですね。renderメソッドに限った話ではなくて後述するComponent Life Cycleによってはやってはいけないメソッドも存在します。`

上記の文章入れる場合も、資料として何かしらの記述はあったほうがいいかと。

**4**

`PropTypes`のここはみるだけ
`build`のここからまた書きます

ここの表現が資料としてわかりにくいので、

### build（ここから手を動かす）

とかにしたほうがわかりやすいと思います。

## 直しても直さなくてもいいやつ（任せます）

**雛形の作成**

`余談`の箇所は引用にしたほうが見やすそう？

**Comment by YutamaKotaro** [comment]
**1**  

Reactをやろうとしている手前、ここら辺は省いてあんまり覚えることが増えると大変かと思うので、ここは削除します。聞かれたら答えるスタイルでいきます！

**2**  
省いて、口頭で説明にします！もしかしらた細かい説明を書くかもです！

**3**  

> 上記の文章入れる場合も、資料として何かしらの記述はあったほうがいいかと。

どのメソッドつかうとなるかとかでしょうか？

**4**  

かしこまりました！

**その他**  

説明するかは迷い中なので、説明しないことになったら引用にします。
説明することになったら、もう少し目立つようにして余談を変えます！

**Comment by besutome** [comment]
ありがとうございます！
3に関しては、その通りです！

`Component Life Cycleによってはやってはいけないメソッド`
とあるので、やってはいけないことを説明する形にできればいいと思います
